// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuKWVCP9o6gV8R5MXZASlwzDFdByjHtFQ',
    appId: '1:402812477660:web:5ad53f71cbe86f3afdd419',
    messagingSenderId: '402812477660',
    projectId: 'poppin-s-app',
    authDomain: 'poppin-s-app.firebaseapp.com',
    storageBucket: 'poppin-s-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxdEEe5NeYQW9h3Yp8nTBWXVBFyqbZV8c',
    appId: '1:402812477660:android:56f42037b1299fadfdd419',
    messagingSenderId: '402812477660',
    projectId: 'poppin-s-app',
    storageBucket: 'poppin-s-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWoDgjPjMWGVSZAEgoKHTBVri8BtB4J-k',
    appId: '1:402812477660:ios:1215769eece54217fdd419',
    messagingSenderId: '402812477660',
    projectId: 'poppin-s-app',
    storageBucket: 'poppin-s-app.firebasestorage.app',
    iosClientId: '402812477660-m78fj12if3c9639k6vtlosq1agrg5liv.apps.googleusercontent.com',
    iosBundleId: 'com.example.poppinsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWoDgjPjMWGVSZAEgoKHTBVri8BtB4J-k',
    appId: '1:402812477660:ios:1215769eece54217fdd419',
    messagingSenderId: '402812477660',
    projectId: 'poppin-s-app',
    storageBucket: 'poppin-s-app.firebasestorage.app',
    iosClientId: '402812477660-m78fj12if3c9639k6vtlosq1agrg5liv.apps.googleusercontent.com',
    iosBundleId: 'com.example.poppinsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuKWVCP9o6gV8R5MXZASlwzDFdByjHtFQ',
    appId: '1:402812477660:web:28c80646cb292f87fdd419',
    messagingSenderId: '402812477660',
    projectId: 'poppin-s-app',
    authDomain: 'poppin-s-app.firebaseapp.com',
    storageBucket: 'poppin-s-app.firebasestorage.app',
  );

}